/*
 * Copyright (c) 2016, Devan Lai
 *
 * Permission to use, copy, modify, and/or distribute this software
 * for any purpose with or without fee is hereby granted, provided
 * that the above copyright notice and this permission notice
 * appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
 * WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
 * AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR
 * CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
 * LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
 * NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
 * CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED


// Without this, dfu-util exits with an error on flashing
#define DFU_WILL_DETACH 0

#define USE_HSI 1
#define CLOCK_MHZ 48
#define CLOCK_HZ (CLOCK_MHZ * 1000000)
#define APP_BASE_ADDRESS (0x08000000 + BOOTLOADER_OFFSET)
#define FLASH_SIZE_OVERRIDE 0x100000
#define FLASH_PAGE_SIZE  2048
#define DFU_UPLOAD_AVAILABLE 1
#define DFU_DOWNLOAD_AVAILABLE 1

#define HAVE_LED 0

#define LED_PROG_KEY 3 // The LED in the top left corner

#define HAVE_BUTTON 1
#define BUTTON_ACTIVE_HIGH 1
#define BUTTON_GPIO_PORT GPIOB
#define BUTTON_GPIO_PIN GPIO14
#define BUTTON_USES_PULL 1

#define BUTTON_OUTPUT_GPIO_PORT GPIOB
#define BUTTON_OUTPUT_GPIO_PIN GPIO15

#define BUTTON_SAMPLE_DELAY_CYCLES 1440000

#define HAVE_USB_PULLUP_CONTROL 1

#define USES_GPIOA 1
#define USES_GPIOB 1
#define USES_GPIOC 0

#define USB_PULLUP_GPIO_PORT GPIOA
#define USB_PULLUP_GPIO_PIN  GPIO8
#define USB_PULLUP_ACTIVE_HIGH 1
#define USB_PULLUP_OPEN_DRAIN 0

#define USB_VID 0x3496
#define USB_PID 0x0005


#define USES_I2C_LEDS

#define INNER_STRINGIFY(str) #str
#define STRINGIFY(str) INNER_STRINGIFY(str)

#define LANDING_PAGE_URL "dfu.keyboard.io?vid=" STRINGIFY(USB_VID) ";pid=" STRINGIFY(USB_PID)  ";version=" STRINGIFY(GIT_BUILD_SHA)

#define USB_VENDOR_STRING "Keyboardio"
#define USB_PRODUCT_STRING "Model 100 (Bootloader)"

#endif
